from typing import Protocol

from app.domain.models.token import Token


class TokenRepository(Protocol):
    def load(self) -> Token: ...
    def save(self, token: Token) -> None: ...
    def get(self) -> Token: ...
    def set(self, token: Token) -> None: ...
